version: '3'
services:
  webapp:
    container_name: webapp
    build:
      .
    ports:
      - "8080:80"
    depends_on:
      - db
   
  db:
    container_name: mysql_db
    image: mysql
    volumes:
      - /Users/charlesfranca/Documents/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root